interface = "en???"             # Name of network interface to use
bot_token = "<token>"           # Telegram bot token (https://core.telegram.org/bots/api#authorizing-your-bot)
cooldown = "5m"                 # Optional: Duration to wait before sending another notification for the same user

[quiet_period]                  # Optional: Time period when messages will have disabled notifications
start = "23:00"
end = "06:00"

[[user]]
name = "User 1"                 # Name of user
icon = "👩"                     # Optional: Icon to identify user
username = "user1"              # Optional: Telegram username to link to in notification
chat_id = 123456                # Chat ID for bot to notify in, required if user is a subscriber
subscriber = "User 2"           # Who to notify, requires at least one device
[[user.device]]
hostname = "myphone"            # Optional: Hostname of device, used to detect if connect on startup
mac = "01:23:45:67:89:AB"       # MAC address belonging to user, required if user has subscriber

[[user]]
name = "User 2"
username = "user2"
chat_id = 654321
subscriber = "User 1"
[[user.device]]
mac = "00:11:22:33:44:55"
