name: CI

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
    - uses: actions/checkout@master
    - name: Format
      run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
    - uses: actions/checkout@master
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
    - uses: actions/checkout@master
    - name: Check
      run: cargo check --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    needs: [format, lint, build]
    matrix:
      rust: [stable, nightly]
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install dependencies
      run: sudo apt install libpcap-dev
    - uses: actions/checkout@master
    - name: Test
      run: cargo test --all-features
